In [1]:
import pandas as pd
import unidecode  # <- para eliminar tildes

# Cargar el CSV limpio
ruta = r"C:\Users\pablo\proyecto\comparador\alquiler_unificado_con_coordenadas_limpio.csv"
df = pd.read_csv(ruta)

# Función para extraer tipo desde texto
def detectar_tipo(texto, tipo):
    texto = unidecode.unidecode(str(texto).lower())  # minúsculas sin tildes
    return tipo in texto

# Palabras clave a buscar
tipos = {
    "piso": "es_piso",
    "casa": "es_casa",
    "atico": "es_atico",
    "estudio": "es_estudio",
    "apartamento": "es_apartamento",
    "duplex": "es_duplex",
    "chalet": "es_chalet",
    "finca": "es_finca",
    "loft": "es_loft"
}

# Crear columnas
for palabra, columna in tipos.items():
    df[columna] = df["titulo"].apply(lambda x: detectar_tipo(x, palabra))

# Guardar archivo actualizado
ruta_salida = r"C:\Users\pablo\proyecto\comparador\alquiler_con_tipos_detectados.csv"
df.to_csv(ruta_salida, index=False)

print(f"✅ Archivo actualizado guardado en:\n{ruta_salida}")

✅ Archivo actualizado guardado en:
C:\Users\pablo\proyecto\comparador\alquiler_con_tipos_detectados.csv

In [3]:
df[["titulo", "es_piso", "es_casa", "es_atico", "es_estudio", "es_apartamento", "es_duplex", "es_chalet", "es_finca", "es_loft"]].head(10)

,titulo,es_piso,es_casa,es_atico,es_estudio,es_apartamento,es_duplex,es_chalet,es_finca,es_loft
0,Piso en calle Luis Garcia Cereceda,True,False,False,False,False,False,False,False,False
1,Piso en calle Libertad,True,False,False,False,False,False,False,False,False
2,Casa unifamiliar en calle XIX,False,True,False,False,False,False,False,False,False
3,Piso en calle de Ponzano,True,False,False,False,False,False,False,False,False
4,Piso en Zona Avenida de Europa,True,False,False,False,False,False,False,False,False
5,"Piso en calle de Gravina, 15",True,False,False,False,False,False,False,False,False
6,Ático en La Navata,False,False,True,False,False,False,False,False,False
7,"Estudio en calle de Pollensa, 5",False,False,False,True,False,False,False,False,False
8,Piso en Colonia de los Ángeles,True,False,False,False,False,False,False,False,False
9,Piso en calle del Marqués de Lozoya,True,False,False,False,False,False,False,False,False